export const projects = [
  {
    title: 'Taylor Winfrey',
    description: "The greatest band ever conceived",
    image: '/images/TW.gif',
    tags: ['PostgreSQL', 'Express', 'React', 'Node'],
    code: 'https://github.com/chuckhalliday/TaylorWinfrey',
    visit: 'https://soft-arithmetic-d579e0.netlify.app/',
    id: 0,
  },
  {
    title: 'Give Me 40 Bucks',
    description:"The greatest way to give me 40 bucks",
    image: '/images/40dollars.jpeg',
    tags: ['Vue', 'Bulma', 'Django', 'Stripe.js'],
    code: 'https://github.com/chuckhalliday/FortyBucks',
    visit: 'https://www.givemefortybucks.com/',
    id: 1,
  },
  /* {
    title: 'Advisor.Autos',
    description: "The greatest way to service your car",
    image: '/images/AdvisorLights.png',
    tags: ['MongoDB', 'Swift'],
    code: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Consent Party',
    description: "The greatest place to get the big D",
    image: '/images/ConsentChecks.png',
    tags: ['Next.js'],
    code: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  }, */
];

export const TimeLineData = [
  { year: 2007, text: 'Graduated Fairfield Ludlowe High School', },
  { year: 2008, text: 'Attended University of Montana for Audio Engineering and Music Composition', },
  { year: 2009, text: 'Spent summer working on boats and in canneries in Homer, Alaska', },
  { year: 2010, text: 'Traveled extensively, eventually hitting all 50 states and most of Canada', },
  { year: 2011, text: 'Moved to Anchorage, Alaska', },
  { year: 2012, text: 'Promoted to sales management and recruitment at Kirby Company', },
  { year: 2013, text: 'Worked two simultaneous jobs selling mobile devices and home furnishings', },
  { year: 2014, text: 'Learned B2B sales at Fastenal Company', },
  { year: 2015, text: 'Returned to home furnishings in specialty market', },
  { year: 2016, text: 'Moved to Portland, Oregon', },
  { year: 2017, text: 'Became Chevy/GM Certified', },
  { year: 2018, text: 'Became Subaru Certified and achieved highest personal sales month - 18 vehicles', },
  { year: 2019, text: 'Took on position as Service Advisor, averaging $875,000 annually in personal sales', },
  { year: 2020, text: 'Began web development journey', },
  { year: 2021, text: 'Deployed my first full stack-application', },
  { year: 2022, text: 'Expanded my knowledge of algorithms, data structures, and machine learning', },
  { year: 2023, text: 'Continue to apply my ever expanding skill sets to personally motivating artistic endeavors', },
];